baseURL      = 'https://ranjanphukan.com/'
languageCode = 'en-us'
title        = 'Ranjan Phukan'

[params]
  description = "Ranjan Phukan personal website"
  keywords    = "Ranjan Phukan, personal website, blog, portfolio"
  avatar      = "img/ranjan.jpg"
  custom_css  = ["css/custom.css"]

  [params.author]
    name = 'Ranjan Phukan'
  

# Add theme using Hugo modules
[module]
  [[module.imports]]
    path = "github.com/hugo-porto/theme"

[caches]
  [caches.images]
    dir = ':cacheDir/images'